[package]
name = "anti-anti-ananas"
version = "0.1.0"
edition = "2018"

[dependencies]
actix-web = "4.0.0-beta.8"
actix-rt = "2"
actix-files = "0.6.0-beta.7"
rand = "0.8"
anyhow = "1.0"
serde = { version = "1.0", features = [ "derive"]}

[profile.release]
lto = "fat"
codegen-units = 1