version: '3'
services:
  app:
    build:
      context: .
    environment:
      - LISTEN_ADDRESS=0.0.0.0:3000
      - MESSAGE_FILE=./messages.txt
      - VIRTUAL_HOST=anti-anti-ananas.club
      - VIRTUAL_PORT=3000
      - LETSENCRYPT_HOST=anti-anti-ananas.club